name: vietqr

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: '>=3.5.0 <4.0.0'

    dependencies:
      dart_mappable: ^4.5.0

    dev_dependencies:
      lints: ^5.0.0
      test: ^1.24.0
      build_runner: ^2.5.2
      dart_mappable_builder: ^4.5.0