name: vietqr

sdkPath: .fvm/flutter_sdk

packages:
  - packages/**

ignore:
  - "packages/**/example"
  - "packages/**/example/**"

command:
  bootstrap:
    environment:
      sdk: '>=3.5.0 <4.0.0'

version:
  workspaceChangelog: true
  updateGitTagRefs: true
  includeScopes: true
  conventionalCommits: true