name: vietqr_core
description: A pure Dart library for encoding and decoding VietQR data according to the EMVCo standard. Suitable for both client and server environments.
version: 0.2.5
homepage: https://github.com/vanvixi/vietqr.dart
repository: https://github.com/vanvixi/vietqr.dart/tree/main/packages/vietqr_core
issue_tracker: https://github.com/vanvixi/vietqr.dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


topics:
  - qr
  - vietqr
  - banking
  - vietnam
  - payment
