name: vietqr_core
description: A pure Dart library for encoding and decoding VietQR data according to the EMVCo standard. Suitable for both client and server environments.
version: 0.2.2
homepage: https://github.com/vanvixi/vietqr.dart/tree/main/packages/vietqr_core
repository: https://github.com/vanvixi/vietqr.dart
issue_tracker: https://github.com/vanvixi/vietqr.dart/issues

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dart_mappable: 4.3.1

dev_dependencies:
  test: ^1.24.0
  build_runner: 2.4.10
  dart_mappable_builder: 4.3.1


topics:
  - qr
  - vietqr
  - banking
  - vietnam
  - payment
