name: vietqr_core
resolution: workspace
description: A pure Dart library for encoding and decoding VietQR data according to the EMVCo standard. Suitable for both client and server environments.
version: 0.1.0
homepage: https://github.com/vanvixi/vietqr.dart/tree/main/packages/vietqr_core
repository: https://github.com/vanvixi/vietqr.dart
issue_tracker: https://github.com/vanvixi/vietqr.dart/issues
publish_to: "https://pub.dev"

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
