name: vietqr_widget
resolution: workspace
description: A Flutter UI widget to display VietQR codes. Built on top of vietqr_encode and vietqr_image.
version: 0.1.0
homepage: https://github.com/vanvixi/vietqr.dart/tree/main/packages/vietqr_widget
repository: https://github.com/vanvixi/vietqr.dart
issue_tracker: https://github.com/vanvixi/vietqr.dart/issues
publish_to: "https://pub.dev"

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
