name: vietqr_widget
resolution: workspace
description: A Flutter UI widget to display VietQR codes. Built on top of vietqr_encode.
version: 0.1.1
homepage: https://github.com/vanvixi/vietqr.dart
repository: https://github.com/vanvixi/vietqr.dart/tree/main/packages/vietqr_widget
issue_tracker: https://github.com/vanvixi/vietqr.dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  vietqr_core: ^0.2.4
  pretty_qr_code: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0


topics:
  - qr
  - vietqr
  - banking
  - vietnam
  - payment