name: vietqr_image
resolution: workspace
description: A Dart package to generate QR images (PNG, JPEG, etc.) from VietQR EMVCo data. Works on both Flutter and Dart server environments.
version: 0.1.0
homepage: https://github.com/vanvixi/vietqr.dart/tree/main/packages/vietqr_image
repository: https://github.com/vanvixi/vietqr.dart
issue_tracker: https://github.com/vanvixi/vietqr.dart/issues
publish_to: "https://pub.dev"

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
